dist: trusty
cache:
  directories:
    - node_modules
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
  - npm run test
sudo: required
